language: node_js

node_js:
  - 'stable'

cache:
  directories:
  - node_modules

script:
  - yarn test --watchAll=false #lance les tests
  - yarn build #lance le build

install:
  - yarn

on:
  branch: master

deploy:
  - provider: heroku #connexion avec heroku
  - api_key: $HEROKU_KEY #varibale d'environnement que l'on place dans les settings du projet travis
  - app: $HEROKU_APP